### ISSUE TITLE
ASCII BTL File

### ISSUE THREAD

**Issue by upsonp** [pyoceans/python-ctd#141]
I notice at the top of the `from_btl(fname)` function that it says:

```DataFrame constructor to open Seabird CTD BTL-ASCII format.```

But the `_read_file(fname)` function is actually opening the file with a UTF-8 encoding.

My work around at the moment is to open the BTL file in NotePad++ and convert the ASCII files to UTF-8, but maybe we could pass the file encoding as `from_btl(fname, encoding='utf-8')`, then `_read_file(fname, encoding='utf-8')`. Doing so shouldn't change the existing behavior, but will give the option for the developer to set the file encoding if necessary.

Thoughts?

**Comment by ocefpaf** [comment]
Adding options may be confusing but assuming that all data is UTF-8 is probably worse. Can you check if https://github.com/pyoceans/python-ctd/pull/145 works for you case?

**Comment by upsonp** [comment]
This was actually not as big of a deal as I thought. If we allow the user to pass in a StringIO as `fname` for issue #142, then the user can create their own IO Stream for whatever file type and encoding they're trying to read.

**Comment by ocefpaf** [comment]
Cool. I'll merge #145 then and close this one so we can focus on the stream input.
