### ISSUE TITLE
include "prDE" in pressure keys inside from_cnv function 

### ISSUE THREAD

**Issue by MDHDZ91** [pyoceans/python-ctd#159]
I am working with .cnv files that have "prDE" as the pressure heading so I had to add "prDE" to prkeys in the from_cnv function to be able to read my files and process them. Would be great if "prDE" was added to keys in case other users have a similar issue. Thank you.

**Comment by ocefpaf** [comment]
Do you want to send a PR for that?

**Comment by MDHDZ91** [comment]
done, thanks! 
(this is my first time, so I hope I did it correctly!)

**Comment by MDHDZ91** [comment]
I am now getting this error:
"ValueError: Expected one pressure/depth column, got ['depFM', 'prDE']. Check your input data."

While my files have both ['depFM', 'prDE'], only 'prDE' is in the list of accepted keys so I am not sure why this is happening. 
Perhaps we should add an if statement that if both of these columns are found use the pressure key? some of my files have prDE and other prDM, but all have both the depth and pressure columns.

**Comment by ocefpaf** [comment]
Can you share the file header?

**Comment by MDHDZ91** [comment]
This is for the file I shared previously.

María D. Hernández Limón
Coleman Lab  <http://biogeolabs.uchicago.edu/colemanlab/>
PhD Candidate
Dept. of the Geophysical Sciences
University of Chicago
(224)-772-4017

UChicago-DAB Member
<https://voices.uchicago.edu/uchicagograd/2019/10/17/meet-the-uchicagograd-diversity-advisory-board-dab/>
| PSD EDI Student Committee Member
<https://physicalsciences.uchicago.edu/about/diversity-inclusion/committees/edi-student-committee/>
Neubauer Fellow <https://grad.uchicago.edu/fellowships/neubauer-fellows/>|DSEER
NSF Fellow <https://voices.uchicago.edu/nrtenergyandenvironment/about/>| Ford
Foundation Predoctoral Fellow
<https://sites.nationalacademies.org/PGA/FordFellowships/index.htm>

**Comment by ocefpaf** [comment]
> This is for the file I shared previously.

You'll have to either copy the text here or "drag-n-drop" into the GH issue comment box. When you attach it from your email GH scrubs the file. See https://github.com/pyoceans/python-ctd/issues/159#issuecomment-1256495418.

**Comment by MDHDZ91** [comment]
I think this is the relevant part of the header portion of the .cnv file:
Note that there is a depFM column and prDE (they key we just added), other files have depFM and prDM(already included in keys). So as long as depFM is not in the keys there should not be any issues so I am unsure why I do get the error of having multiple keys. 

* Sea-Bird SBE 9 Data File:
* FileName = C:\Data\2013 Data\Summer Survey\Erie\ER91M.hex
* Software Version Seasave V 7.21f
* Temperature SN = 5394
* Conductivity SN = 3828
* Number of Bytes Per Scan = 34
* Number of Voltage Words = 5
* Number of Scans Averaged by the Deck Unit = 1
* System UpLoad Time = Aug 09 2013 22:54:10
* NMEA Latitude = 41 50.46 N
* NMEA Longitude = 082 54.99 W
* NMEA UTC (Time) = Aug 10 2013 02:54:08
* Store Lat/Lon Data = Append to Every Scan
* SBE 11plus V 5.2
* number of scans to average = 1
* pressure baud rate = 9600
* NMEA baud rate = 4800
* surface PAR voltage added to scan
* A/D offset = 4
* Latitude/Longitude added to scan
* GPIB address = 1
* advance primary conductivity  0.073 seconds
* advance secondary conductivity  0.073 seconds
* delete word 3 from scan
* delete word 4 from scan
* autorun on power up is disabled
* S>
** Ship: Lake Guardian
** Cruise: Summer Survey
** Station:  ER91M
* System UTC = Aug 10 2013 02:54:10
# nquan = 17
# nvalues = 11721                                 
# units = specified
# name 0 = depFM: Depth [fresh water, m]
# name 1 = t090C: Temperature [ITS-90, deg C]
# name 2 = c0mS/cm: Conductivity [mS/cm]
# name 3 = sbeox0Mg/L: Oxygen, SBE 43 [mg/l]
# name 4 = par: PAR/Irradiance, Biospherical/Licor
# name 5 = altM: Altimeter [m]
# name 6 = bat: Beam Attenuation, Chelsea/Seatech [1/m]
# name 7 = xmiss: Beam Transmission, Chelsea/Seatech [%]
# name 8 = prDE: Pressure, Digiquartz [psi]
# name 9 = ptempC: Pressure Temperature [deg C]
# name 10 = flSP: Fluorescence, Seapoint
# name 11 = specc: Specific Conductance [uS/cm]
# name 12 = spar: SPAR/Surface Irradiance
# name 13 = upoly0: Upoly 0, SUNA Nitrate Sensor
# name 14 = upoly1: Upoly 1, DO, mg/L Optode 4330FA
# name 15 = upoly2: Upoly 2, Temp, C Optode 4330FA
# name 16 = flag:  0.000e+00
# span 0 =     -0.848,      8.988                 
# span 1 =    21.4710,    22.9570                 
# span 2 =   0.014505,   0.235256                 
# span 3 =    4.94156,    9.53810                 
# span 4 = 1.0000e-12, 1.0991e+01                 
# span 5 =       0.42,      98.56                 
# span 6 =    -0.0741,     3.9759                 
# span 7 =    37.0099,   101.8693                 
# span 8 =     -1.206,     12.784                 
# span 9 =      21.61,      21.67                 
# span 10 = 1.1722e-01, 1.3996e+01                
# span 11 =     15.520,    245.523                
# span 12 = 0.0000e+00, 0.0000e+00                
# span 13 = -0.0691891,  0.2495048                
# span 14 =  2.5409035,  2.7704518                
# span 15 =  21.246642,  23.024420                
# span 16 = 0.0000e+00, 0.0000e+00                
# interval = seconds: 0.0416667

**Comment by MDHDZ91** [comment]
The read_cnv function I was troubleshooting works with the addition on prDE but when I try to run the function from the updated ctd package I get the error. To run the read_cnv function I copied the code plus all the code it needed so somewhere I must of dropped the code were the issue starts. I have over 2k files and I am unsure how many have prDE or prDM but all have depFM.

**Comment by MDHDZ91** [comment]
I still can't figure out why this error happens, since depFM is not in the column keys the function should not be reading it. Any ideas?

**Comment by MDHDZ91** [comment]
I uninstalled the module from the env and re-installed and now I don't have this issue. Hopefully it stays this way.

**Comment by ocefpaf** [comment]
> I uninstalled the module from the env and re-installed and now I don't have this issue. Hopefully it stays this way.

Can you send me the version you have installed*? I don't recall the logic to choose depth vs pressure when both are present but we may need to adjust that.

\* if using conda `conda list ctd` or, if using pip, `pip freeze`.

**Comment by MDHDZ91** [comment]
<img width="1189" alt="Screen Shot 2022-09-30 at 9 53 50 AM" src="https://user-images.githubusercontent.com/22032389/193298041-92814a16-6f8c-42f4-9fb1-565323931eae.png">

<img width="1182" alt="Screen Shot 2022-09-30 at 9 55 47 AM" src="https://user-images.githubusercontent.com/22032389/193298091-22763916-dc3e-41f7-8ae4-093f880ef8fd.png">

**Comment by MDHDZ91** [comment]
installed with conda
<img width="1182" alt="Screen Shot 2022-09-30 at 9 55 47 AM" src="https://user-images.githubusercontent.com/22032389/193298259-c5ece163-d370-4683-9360-9bffcd375fbc.png">

installed by pulling from git and grabbing the functions directly from the .py scripts
<img width="1190" alt="Screen Shot 2022-09-30 at 9 56 01 AM" src="https://user-images.githubusercontent.com/22032389/193298379-a519a467-4add-4704-800a-7926b896a40a.png">

**Comment by MDHDZ91** [comment]
Since my message saying it worked after reinstalling coda....it didn't...so I decided to move forward with reading the functions from the .py because I could not figure out where the 'depFM' was being read from in the conda module.

**Comment by MDHDZ91** [comment]
This is so embarrassing but **I** am the source of the error. Upon looking closer at the .py within the .conda  I found that I added "depFM" to the script along with "prDE" and this was the version in my conda env. While I thought I updated the package I was still using 1.4.1 which had the code I edited. So I uninstalled it and installed 1.4.2, checked the code to make sure the "depFM" was not where I had it in 1.4.1 and now it works!!

<img width="1126" alt="Screen Shot 2022-09-30 at 10 17 57 AM" src="https://user-images.githubusercontent.com/22032389/193302760-09d35f6d-6384-43e4-8b5f-58f1da70dd11.png">

I am so sorry!

**Comment by ocefpaf** [comment]
> This is so embarrassing but **I** am the source of the error. Upon looking closer at the .py within the .conda I found that I added "depFM" to the script along with "prDE" and this was the version in my conda env.

Been there, done that. There is nothing to be embarrassed about.

> While I thought I updated the package I was still using 1.4.1 which had the code I edited. So I uninstalled it and installed 1.4.2, checked the code to make sure the "depFM" was not where I had it in 1.4.1 and now it works!!

Awesome. Glad it is working!
