### ISSUE TITLE
Add a interpolate_cast method

### ISSUE THREAD

**Issue by ocefpaf** [pyoceans/python-ctd#73]
Should be the normal pandas interpolation with the options:

```python
.interpolate(
    method='index',
    limit_direction='both',
    limit_area='inside'
)
```

That would avoid extrapolation beyond the data domain and would obey the index spacing.

**Comment by rsignell-usgs** [comment]
Is this how we would get to values at fixed levels, like `z = [1, 2, 3, 4 ]` meters depth?

I was wondering how to do that here: https://gist.github.com/rsignell-usgs/61dc61cbd62bc0a52a6198977303ee10

**Comment by ocefpaf** [comment]
Yep. That is the best way to have the data in an arbitrary `z ` instead of the bin center. Take a look at cells 4-5 in https://nbviewer.jupyter.org/gist/ocefpaf/05f8e3fad3ea5f3e57dda77912e58037

I want to implement that as a method here for a while.

**Comment by ocefpaf** [comment]
It turns out that I forgot I already implemented this a while back in https://github.com/pyoceans/python-ctd/pull/71 and you can just do a `.bindata(delta=1, method="interpolate")` instead.
