### ISSUE TITLE
Checking 'pressure' upon reading cnv file

### ISSUE THREAD

**Issue by renochoi** [pyoceans/python-ctd#94]
Hello,

Accessing a bunch of CNV files from last 4 years of observation has been in trouble using python-ctd module. My CNV files has no 'pressure' record and the python-ctd module shows the following errors,

```python
>>> cast = ctd.from_cnv('/Users/reno/Downloads/ctd_sample/Gisang1_New2020.8.22.2005.cnv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/reno/anaconda3/lib/python3.8/site-packages/ctd/read.py", line 387, in from_cnv
    raise ValueError(f"Expectd one pressure column, got {prkey}.")
ValueError: Expectd one pressure column, got [].

Checking the CNV file,

# name 0 = depSM: Depth [salt water, m], lat = 0.00
# name 1 = t090C: Temperature [ITS-90, deg C]
# name 2 = sal00: Salinity, Practical [PSU]
# name 3 = sbeox0ML/L: Oxygen, SBE 43 [ml/l]
# name 4 = ph: pH
# name 5 = altM: Altimeter [m]
# name 6 = pumps: Pump Status
# name 7 = flag:  0.000e+00
```

Is 'pressure' absolutely necessary in python-ctd module?

**Comment by ocefpaf** [comment]
Not really. We should not fail on those edge cases. I'll add some code to load the file regardless. Or maybe you want to send a PR?

**Comment by richardsc** [comment]
Not related to this python module, but for comparison in the `oce` package in R we load the file if it has depth but not pressure, then create a `pressure` variable (along with a warning).

**Comment by ocefpaf** [comment]
Thanks. That is similar to what I was thinking but without the automated pressure calculation. I guess that since we already depend on gsw we can just do that.

**Comment by renochoi** [comment]
I temporarily opt out the pressure-related-contrstraint in the code and it works now. Nonetheless, I wonder if it related to other functionalities regarding quality control, such as de-noise etc.

**Comment by ocefpaf** [comment]
@renochoi do you have a small file with that characteristic that you can share? I want to create some test for it. I'm working on a way to warn users and, if the expected information is all there, guide them on how to compute the pressure.

**Comment by ocefpaf** [comment]
Done in #96 

Still missing proper tests though.
