### ISSUE TITLE
plot_section function in ctd

### ISSUE THREAD

**Issue by hpaixt** [pyoceans/python-ctd#98]
When I read  the book《R AND PYTHON FOR OCEANOGRAPHERS》，I found the auther used python packkage CTD like this :from ctd import plot_section,but when I used in my code the error happpened,so I read the source code of CTD ,there is no function named plot_section,why?

**Comment by ocefpaf** [comment]
The library had a refactor and we are still gauging if it is worth to wrap plotting functions like that or let users roll their own plotting. Here is an example that you can use and adapt: https://nbviewer.jupyter.org/gist/ocefpaf/a60829de834e8c0b631b89cfd71d34c8
